version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  worker:
    build: .
    container_name: video-processor-worker
    depends_on:
      - redis
      - minio
    environment:
      REDIS_HOST: redis:6379
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./tmp:/tmp
    # Se quiser rodar em modo interativo para debug, descomente:
    # tty: true

volumes:
  minio_data: 