package processor

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	oteltrace "go.opentelemetry.io/otel/trace"
	"github.com/rs/zerolog/log"

	processor_steps "video-processor/internal/processor/processor-steps"
	"video-processor/internal/telemetry"
	"video-processor/metrics"
)

// Individual timeouts per pipeline step.
const (
	stepTimeoutValidate   = 30 * time.Second
	stepTimeoutAnalyze    = 30 * time.Second
	stepTimeoutTranscode  = 3 * time.Minute
	stepTimeoutThumbnails = 60 * time.Second
	stepTimeoutAudio      = 2 * time.Minute
	stepTimeoutPreview    = 2 * time.Minute
	stepTimeoutStreaming  = 4 * time.Minute
)

// ProcessingResult contains the paths of artifacts generated by the pipeline.
// TempDir should be removed by the caller after uploads.
type ProcessingResult struct {
	TempDir       string
	ThumbnailsDir string
	AudioPath     string
	PreviewPath   string
	StreamingDir  string
	Metadata      *processor_steps.VideoMetadata
}

// ProcessVideo executes all steps of the video processing pipeline.
func ProcessVideo(ctx context.Context, inputPath, outputPath string) (*ProcessingResult, error) {
	baseDir := filepath.Dir(outputPath)
	videoBaseName := filepath.Base(inputPath)
	videoBaseName = videoBaseName[:len(videoBaseName)-len(filepath.Ext(videoBaseName))]

	tempDir := filepath.Join(baseDir, videoBaseName+"_temp")
	if err := os.MkdirAll(tempDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create temp directory: %w", err)
	}

	result := &ProcessingResult{TempDir: tempDir}

	// 1. Validation
	log.Info().Msg("Step 1/7: Validating video")
	if err := runStep(ctx, "validate", stepTimeoutValidate, func(stepCtx context.Context) error {
		return processor_steps.ValidateVideo(stepCtx, inputPath)
	}); err != nil {
		return result, fmt.Errorf("validation failed: %w", err)
	}

	// 2. Content analysis
	log.Info().Msg("Step 2/7: Analyzing content")
	_ = runStep(ctx, "analyze", stepTimeoutAnalyze, func(stepCtx context.Context) error {
		metadata, err := processor_steps.AnalyzeContent(stepCtx, inputPath)
		if err != nil {
			log.Warn().Err(err).Msg("Content analysis failed")
			return err
		}
		result.Metadata = metadata
		return nil
	})

	// 3. Transcoding (critical step)
	log.Info().Msg("Step 3/7: Transcoding video")
	if err := runStep(ctx, "transcode", stepTimeoutTranscode, func(stepCtx context.Context) error {
		return processor_steps.TranscodeVideo(stepCtx, inputPath, outputPath)
	}); err != nil {
		return result, fmt.Errorf("transcoding failed: %w", err)
	}

	transcodedPath := outputPath

	// 4. Thumbnail generation
	log.Info().Msg("Step 4/7: Generating thumbnails")
	thumbnailsDir := filepath.Join(tempDir, "thumbnails")
	if err := runStep(ctx, "thumbnails", stepTimeoutThumbnails, func(stepCtx context.Context) error {
		return processor_steps.GenerateThumbnails(stepCtx, transcodedPath, thumbnailsDir)
	}); err != nil {
		log.Warn().Err(err).Msg("Failed to generate thumbnails")
	} else {
		result.ThumbnailsDir = thumbnailsDir
	}

	// 5. Audio extraction
	log.Info().Msg("Step 5/7: Extracting audio")
	audioPath := filepath.Join(tempDir, "audio.mp3")
	if err := runStep(ctx, "audio", stepTimeoutAudio, func(stepCtx context.Context) error {
		return processor_steps.ExtractAudio(stepCtx, transcodedPath, audioPath)
	}); err != nil {
		log.Warn().Err(err).Msg("Audio extraction failed")
	} else {
		result.AudioPath = audioPath
	}

	// 6. Preview generation
	log.Info().Msg("Step 6/7: Generating preview")
	previewPath := filepath.Join(tempDir, "preview.mp4")
	if err := runStep(ctx, "preview", stepTimeoutPreview, func(stepCtx context.Context) error {
		return processor_steps.GeneratePreview(stepCtx, transcodedPath, previewPath)
	}); err != nil {
		log.Warn().Err(err).Msg("Preview generation failed")
	} else {
		result.PreviewPath = previewPath
	}

	// 7. Streaming segmentation
	log.Info().Msg("Step 7/7: Segmenting for streaming")
	streamingDir := filepath.Join(tempDir, "streaming")
	if err := runStep(ctx, "streaming", stepTimeoutStreaming, func(stepCtx context.Context) error {
		return processor_steps.SegmentForStreaming(stepCtx, inputPath, streamingDir)
	}); err != nil {
		log.Warn().Err(err).Msg("Streaming segmentation failed")
	} else {
		result.StreamingDir = streamingDir
	}

	log.Info().Msg("Processing pipeline completed successfully")
	return result, nil
}

// runStep executes a pipeline step within an OTel span and records duration via Prometheus.
// The span is marked as error if the step fails.
func runStep(ctx context.Context, name string, timeout time.Duration, fn func(context.Context) error) error {
	stepCtx, span := telemetry.Tracer().Start(ctx, "step/"+name,
		oteltrace.WithAttributes(attribute.String("step.name", name)),
	)
	defer span.End()

	stepCtx, cancel := context.WithTimeout(stepCtx, timeout)
	defer cancel()

	start := time.Now()
	err := fn(stepCtx)
	metrics.ProcessingStepDuration.WithLabelValues(name).Observe(time.Since(start).Seconds())

	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}
